### ISSUE TITLE
Question: why does Pony have the six capabilities that it has?

### ISSUE THREAD

**Issue by JobLeonard** [CausalityLtd/pony-tutorial#18]
Hey all. I'm just working my way through the tutorial and trying to make sense of the reason for certain design decisions. As in, how it all clicks together.

I'm trying to wrap my head around capabilities, Pony's secret sauce. I think I'm looking at this from a slightly wrong angle, and fail to make the necessary step to look at it from the right perspective to see how capabilities click together. If I get the fundamental idea of capabilities right, they effectively tell me something about:

* whether the *current* actor might have *read* access or not
* whether the *current* actor might have *write* access or not
* whether *other* actors might have *read* access or not
* whether *other* actors might have *write* access or not

It does this through *denying* different types of aliasing. However, if I combine that list above, I get sixteen unique combinations, no? Yet Pony has just six capabilities. So my question is: what elimination step am I missing?

I assume ten of those sixteen combinations simply make no sense? For example, [in  the Curry On!-talk there's a matrix with only three rows and columns](https://www.youtube.com/watch?v=KvLjy8w1G_U&feature=youtu.be&t=296), of which three cells are not used because "they don't make any sense." The thing is, it's not immediately evident to me why it isn't?

(mind you, this is the first time I hear of capabilities, and I've never worked with an actor model before, so this is all new to me)

**Comment by andymcn** [comment]
You are correct that 10 of the 16 possibilities for capabilities don't make sense. Here's why.

Firstly we don't let anyone have write permission without also having read permission (in deny terminology that means anyone who can't read automatically can't write either). Having write-only data is rather weird and not very helpful, so we just don't allow it. That takes us from a 4x4 grid to a 3x3 grid, so only 9 possibilities left.

One of those is the current actor can't read or write the object and neither can any other actors. So you have an object that no-one can access. Again, that's not very helpful.

Another possibility is that the current actor does not have write access and no other actors have read or write access. So we have a read-only object that only one actor is allowed to read. Since we're trying to make data safe to share this doesn't help us. The object is already restricted to being used only by one actor, making it read-only as well doesn't gain us anything useful.

The final possibility is that the current actor does not have read or write permission and other actors do not have write permission. So we have a read-only object that the current object is not allowed to read. Again this doesn't add anything useful.

Removing all of those gets us down to the 6 capabilities Pony uses.

**Comment by JobLeonard** [comment]
thanks!

**Comment by MrMormon** [comment]
> The final possibility is that the current actor does not have read or write permission and other actors do not have write permission. So we have a read-only object that the current object is not allowed to read. Again this doesn't add anything useful.

That sounds like `tag` to me, but since this issue is closed I guess the exact reasons don't belong in the tutorial. However, this is the only good explanation I remember finding so far, so I'll add this here:

http://cdn.rawgit.com/sylvanc/pony-lecture/master/agere2015.html#/6/8

> The other spaces in the matrix stay empty, because we can't locally deny aliases that we don't globally deny.
